force-app/main/default/objects/WhatsApp_Message__c/fields/Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Name__c</fullName>
    <label>Agent Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Message_Content__c</fullName>
    <label>Message Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Sent_Time__c.field-meta.xml
<CustomField>
    <fullName>Message_Sent_Time__c</fullName>
    <label>Message Sent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Outgoing__c.field-meta.xml
<CustomField>
    <fullName>Outgoing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Outgoing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WhatsAppLwcHelperClass.cls
public with sharing class WhatsAppLwcHelperClass {
  @AuraEnabled
  public static List<WhatsApp_Message__c> listAllMessages(
    String customerPhone
  ) {
    List<WhatsApp_Message__c> allMessages = new List<WhatsApp_Message__c>();
    try {
      if (String.isEmpty(customerPhone)) {
        throw new AuraHandledException(
          'Customer phone number cannot be null or empty.'
        );
      }
      allMessages = [
        SELECT
          Id,
          Name,
          Message_Content__c,
          Message_Type__c,
          Customer_Name__c,
          Customer_Phone__c,
          Agent_Name__c,
          Outgoing__c,
          Message_Sent_Time__c,
          CreatedDate
        FROM WhatsApp_Message__c
        WHERE Customer_Phone__c = :customerPhone
        ORDER BY CreatedDate ASC
      ];
      return allMessages;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static WhatsApp_Message__c sendTextMessage(
    String messageContent,
    String toPhoneNumber
  ) {
    WhatsApp_Message__c message = WhatsAppCallOut.sendTextMessage(
      messageContent,
      toPhoneNumber
    );
    try {
      if (String.isEmpty(messageContent) || String.isEmpty(toPhoneNumber)) {
        throw new AuraHandledException(
          'Message content and phone number cannot be null or empty.'
        );
      }
      return [
        SELECT
          Id,
          Name,
          Message_Content__c,
          Message_Type__c,
          Customer_Name__c,
          Customer_Phone__c,
          Agent_Name__c,
          Outgoing__c,
          Message_Sent_Time__c,
          CreatedDate
        FROM WhatsApp_Message__c
        WHERE Id = :message.Id
        ORDER BY CreatedDate ASC
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static WhatsApp_Message__c getIncomingMessage(
    String recordId,
    String customerPhone
  ) {
    try {
      if (String.isEmpty(recordId) || String.isEmpty(customerPhone)) {
        throw new AuraHandledException(
          'Record ID and customer phone number cannot be null or empty.'
        );
      }
      return [
        SELECT
          Id,
          Name,
          Message_Content__c,
          Message_Type__c,
          Customer_Name__c,
          Customer_Phone__c,
          Agent_Name__c,
          Outgoing__c,
          Message_Sent_Time__c,
          CreatedDate
        FROM WhatsApp_Message__c
        WHERE Id = :recordId AND Customer_Phone__c = :customerPhone
        ORDER BY CreatedDate ASC
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static SObject getCustomerPhoneDynamically(String query) {
    try {
      if (String.isEmpty(query)) {
        throw new AuraHandledException('Query cannot be null or empty.');
      }
      return Database.query(query);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}